config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{registrations: "registrations"}

   root 'vacancies#index'
   get 'vacancies/recent' => 'vacancies#recent'
   resources 'vacancies'

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  belongs_to :company
  has_many :user ,through:  :applieduser



  def self.search(search)
 # where("name LIKE ?", "%#{search}%") 
  #where("content LIKE ?", "%#{search}%")

  where("city LIKE ?","%#{search}%")
  where("technology ILIKE ?","%#{search}%")
 # where("experience LIKE ?","%#{search}%")
  end
end


 

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController


def index
end

  def show
    @vacancy = Vacancy.find(params[:id])
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)

    if @vacancy.save
        redirect_to vacancies_path, notice: "The vacancy has been successfully created"
    end 
  end

  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  def update
    @vacancy = Vacancy.find(params[:id])

    if @vacancy.update_attributes(vacancy_params)
      redirect_to vacancies_path, notice: "The vacancy has been successfully updated"
    end
  end

  def destroy
      @vacancy = Vacancy.find(params[:id])
      @vacancy.destroy
  end
def recent
      #@recent_vacancies = Vacancy.most_recent
      if params[:search]
    @vacancies = Vacancy.search(params[:search]).order("created_at DESC")
  else
    @vacancies = Vacancy.all.order('created_at DESC')
  end
  end
def  addjob

end

  
  private
  def vacancy_params
      params.require(:vacancy).permit!
  end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_vacancy.html.erb
<% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.name %></td>
        <td><%= vacancy.number_of_vacancy%> </td>

      </tr>
    <% end %>

app/views/vacancies/edit.html.erb
<h1>Vacancies#edit</h1>
<p>Find me in app/views/vacancies/edit.html.erb</p>

app/views/vacancies/index.html.erb
<h1>Vacancies#index</h1>
<p>Find me in app/views/vacancies/index.html.erb</p>



	
<%= form_tag(vacancies_recent_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search by city",required: true %>
<%= submit_tag "Search" %>
<% end %>

app/views/vacancies/new.html.erb
<h1>Vacancies#new</h1>
<p>Find me in app/views/vacancies/new.html.erb</p>

app/views/vacancies/recent.html.erb
<% if @vacancies.present? %>
  <table class="table table-bordered table-striped", class: "btn btn-primary">
  	<tr>     
  			<th>Company Name</th>
    		<th>Post Name</th>
            <th>No. of Vacancy</th>
            <th>Technology</th>
            <th>Eligibility</th>
            <th>key Skills</th>
            <th>Location</th>
    		<th colspan:'3'></th>
    	</tr>

  <% @vacancies.each do |vacancy| %>
      <tr>
      	<td><%= vacancy.company.name%> </td>
        <td><%= vacancy.name %></td>
        <td><%= vacancy.number_of_vacancy%> </td>
        <td><%= vacancy.technology%> </td>
        <td><%= vacancy.eligibility%> </td>
        <td><%= vacancy.key_skills%> </td>
        <td><%= vacancy.company.city%>,<%= vacancy.company.state%> </td>
        <td><%= link_to 'Apply',, class: "btn btn-default"  %></td>
      </tr>
    <% end %>
    </table>
<% else %>


  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/vacancies/show.html.erb
<h1>Vacancies#show</h1>
<p>Find me in app/views/vacancies/show.html.erb</p>